# Generated by Django 5.1.5 on 2025-01-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_lavozim_majburiyatlari_maktab_madhiyasi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imtihon_Materiallari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('conclusion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Qongiroqlar_Jadvali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='maktab_madhiyasi',
            name='conclusion',
        ),
        migrations.AddField(
            model_name='qubul_kunlari',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
