# Generated by Django 5.1.5 on 2025-01-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_imtihon_materiallari_ish_qongiroqlar_jadvali_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imtihon_materiallari',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imtihon_materiallari',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imtihon_materiallari',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='imtihon_materiallari',
            name='title_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ish',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ish',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ish',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ish',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ish',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ish',
            name='title_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lavozim_majburiyatlari',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lavozim_majburiyatlari',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lavozim_majburiyatlari',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lavozim_majburiyatlari',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lavozim_majburiyatlari',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lavozim_majburiyatlari',
            name='title_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='maktab_madhiyasi',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maktab_madhiyasi',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maktab_madhiyasi',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='maktab_madhiyasi',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='maktab_madhiyasi',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='maktab_madhiyasi',
            name='title_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='maktab_nizomi',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maktab_nizomi',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maktab_nizomi',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='maktab_nizomi',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='maktab_nizomi',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='maktab_nizomi',
            name='title_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='qongiroqlar_jadvali',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='qongiroqlar_jadvali',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='qongiroqlar_jadvali',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qongiroqlar_jadvali',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qubul_kunlari',
            name='day_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='qubul_kunlari',
            name='day_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='qubul_kunlari',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='qubul_kunlari',
            name='title_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tarkibiy_tuzilma',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarkibiy_tuzilma',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarkibiy_tuzilma',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tarkibiy_tuzilma',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tarkibiy_tuzilma',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tarkibiy_tuzilma',
            name='title_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='field_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='field_uz',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
