# Generated by Django 5.1.5 on 2025-01-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_imtihon_materiallari_content_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='admin_photo/')),
                ('field', models.CharField(max_length=255)),
            ],
        ),
    ]
