# Generated by Django 5.1.5 on 2025-01-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_administrators'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrators',
            name='field_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='administrators',
            name='field_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='administrators',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='administrators',
            name='name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
