# Generated by Django 5.1.5 on 2025-01-30 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_administrators_field_ru_administrators_field_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank='true', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
