# Generated by Django 5.1.5 on 2025-01-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
