# Generated by Django 5.1.5 on 2025-01-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_principal_description_ru_principal_description_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='date_of_birth',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='field',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='reception_days',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='principal',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='principal',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='principal',
            name='image',
            field=models.ImageField(null=True, upload_to='principal_photo/'),
        ),
        migrations.AlterField(
            model_name='principal',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='principal',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
