# Generated by Django 5.1.5 on 2025-01-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_principal_date_of_birth_principal_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='date_of_birth_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='date_of_birth_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='education_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='education_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='field_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='field_uz',
            field=models.TextField(null=True),
        ),
    ]
