# Generated by Django 5.1.5 on 2025-01-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_principal_date_of_birth_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='reception_days_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='reception_days_uz',
            field=models.TextField(null=True),
        ),
    ]
