# Generated by Django 5.1.5 on 2025-01-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_principal_reception_days_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
