# Generated by Django 5.1.5 on 2025-02-02 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_principal_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.CreateModel(
            name='Tugaraklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=255)),
                ('count_of_pupils', models.CharField(max_length=200)),
                ('days', models.TextField()),
                ('time', models.TextField()),
                ('teacher', models.CharField(max_length=255)),
                ('category', models.ForeignKey(blank='true', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
