# Generated by Django 5.1.5 on 2025-02-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_yil_dasturi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qubul_kunlari',
            name='title',
        ),
        migrations.RemoveField(
            model_name='qubul_kunlari',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='qubul_kunlari',
            name='title_uz',
        ),
    ]
