# Generated by Django 5.1.5 on 2025-02-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_qubul_kunlari_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qubul_kunlari',
            name='lunch_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='qubul_kunlari',
            name='lunch_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='qubul_kunlari',
            name='time_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='qubul_kunlari',
            name='time_uz',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
