# Generated by Django 5.1.5 on 2025-02-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_qubul_kunlari_lunch_ru_qubul_kunlari_lunch_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ish',
            name='image_ru',
        ),
        migrations.RemoveField(
            model_name='ish',
            name='image_uz',
        ),
        migrations.RemoveField(
            model_name='ish',
            name='title',
        ),
        migrations.RemoveField(
            model_name='ish',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='ish',
            name='title_uz',
        ),
    ]
