# Generated by Django 5.1.5 on 2025-02-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_ish_image_ru_remove_ish_image_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ish',
            name='conclusion_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ish',
            name='conclusion_uz',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
