# Generated by Django 5.1.5 on 2025-02-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_ish_conclusion_ru_ish_conclusion_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qongiroqlar_jadvali',
            name='date',
        ),
        migrations.RemoveField(
            model_name='qongiroqlar_jadvali',
            name='image',
        ),
        migrations.RemoveField(
            model_name='qongiroqlar_jadvali',
            name='image_ru',
        ),
        migrations.RemoveField(
            model_name='qongiroqlar_jadvali',
            name='image_uz',
        ),
        migrations.RemoveField(
            model_name='qongiroqlar_jadvali',
            name='title',
        ),
        migrations.RemoveField(
            model_name='qongiroqlar_jadvali',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='qongiroqlar_jadvali',
            name='title_uz',
        ),
        migrations.AddField(
            model_name='qongiroqlar_jadvali',
            name='break_duration',
            field=models.PositiveIntegerField(default=5, verbose_name='Перемена (мин)'),
        ),
        migrations.AddField(
            model_name='qongiroqlar_jadvali',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец урока'),
        ),
        migrations.AddField(
            model_name='qongiroqlar_jadvali',
            name='lesson_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер урока'),
        ),
        migrations.AddField(
            model_name='qongiroqlar_jadvali',
            name='shift',
            field=models.CharField(blank=True, choices=[('I', 'Первая смена'), ('II', 'Вторая смена')], max_length=2, null=True, verbose_name='Смена'),
        ),
        migrations.AddField(
            model_name='qongiroqlar_jadvali',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало урока'),
        ),
    ]
