# Generated by Django 5.1.5 on 2025-02-04 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_qongiroqlar_jadvali_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qongiroqlar_jadvali',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Qoʻshilgan sana'),
            preserve_default=False,
        ),
    ]
