# Generated by Django 5.1.5 on 2025-02-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_qongiroqlar_jadvali_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imtihon_materiallari',
            old_name='title',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='imtihon_materiallari',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='imtihon_materiallari',
            name='title_uz',
        ),
    ]
