# Generated by Django 5.1.5 on 2025-02-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_title_imtihon_materiallari_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
