# Generated by Django 5.1.5 on 2025-02-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_teacher_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugaraklar',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
