# Generated by Django 5.1.5 on 2025-02-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_tugaraklar_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugaraklar',
            name='days_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tugaraklar',
            name='days_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tugaraklar',
            name='grade_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tugaraklar',
            name='grade_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tugaraklar',
            name='teacher_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tugaraklar',
            name='teacher_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tugaraklar',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tugaraklar',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
