# Generated by Django 5.1.5 on 2025-02-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_tugaraklar_days_ru_tugaraklar_days_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugaraklar',
            name='year',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
