# Generated by Django 5.1.5 on 2025-02-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_tugaraklar_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='teachers_photo/')),
                ('field', models.CharField(max_length=300)),
                ('phone_number', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
