# Generated by Django 5.1.5 on 2025-02-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_activist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activist',
            old_name='phone_number',
            new_name='grade',
        ),
    ]
