# Generated by Django 5.1.5 on 2025-02-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_huquq_majburiyatlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='huquq_majburiyatlar',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='huquq_majburiyatlar',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='huquq_majburiyatlar',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='huquq_majburiyatlar',
            name='title_uz',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
