# Generated by Django 5.1.5 on 2025-02-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_huquq_majburiyatlar_content_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oquvchilarni_Qabul_Qilish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
