# Generated by Django 5.1.5 on 2025-02-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_oquvchilarni_qabul_qilish'),
    ]

    operations = [
        migrations.AddField(
            model_name='oquvchilarni_qabul_qilish',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oquvchilarni_qabul_qilish',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oquvchilarni_qabul_qilish',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='oquvchilarni_qabul_qilish',
            name='title_uz',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
