# Generated by Django 5.1.5 on 2025-02-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_oquvchilarni_qabul_qilish_content_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xalq_talim',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xalq_talim',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xalq_talim',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='xalq_talim',
            name='title_uz',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
