# Generated by Django 5.1.5 on 2025-02-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_xalq_talim_content_ru_xalq_talim_content_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flag',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gerb',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gerb',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gimn',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gimn',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
