# Generated by Django 5.1.5 on 2025-02-08 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_flag_content_ru_flag_content_uz_gerb_content_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
    ]
