# Generated by Django 5.1.5 on 2025-02-08 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activist',
            options={'verbose_name': 'Активист', 'verbose_name_plural': 'Активисты'},
        ),
        migrations.AlterModelOptions(
            name='administrators',
            options={'verbose_name': 'Карусель Директор', 'verbose_name_plural': 'Карусель Директор'},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория кружков', 'verbose_name_plural': 'Категории кружков'},
        ),
        migrations.AlterModelOptions(
            name='davlat_dasturlari',
            options={'verbose_name': 'Государственная программа', 'verbose_name_plural': 'Государственные программы'},
        ),
        migrations.AlterModelOptions(
            name='flag',
            options={'verbose_name': 'Флаг', 'verbose_name_plural': 'Флаг'},
        ),
        migrations.AlterModelOptions(
            name='gerb',
            options={'verbose_name': 'Герб', 'verbose_name_plural': 'Герб'},
        ),
        migrations.AlterModelOptions(
            name='gimn',
            options={'verbose_name': 'Гимн', 'verbose_name_plural': 'Гимн'},
        ),
        migrations.AlterModelOptions(
            name='huquq_majburiyatlar',
            options={'verbose_name': 'Права и обязанности', 'verbose_name_plural': 'Права и обязанности'},
        ),
        migrations.AlterModelOptions(
            name='imtihon_materiallari',
            options={'verbose_name': 'Экзаминационные материалы', 'verbose_name_plural': 'Экзаменационные материалы'},
        ),
        migrations.AlterModelOptions(
            name='ish',
            options={'verbose_name': 'Свободные вакансии', 'verbose_name_plural': 'Свободные вакансии'},
        ),
        migrations.AlterModelOptions(
            name='lavozim_majburiyatlari',
            options={'verbose_name': 'Должностные обязанности', 'verbose_name_plural': 'Должностные обязанности'},
        ),
        migrations.AlterModelOptions(
            name='maktab_madhiyasi',
            options={'verbose_name': 'Гимн школы', 'verbose_name_plural': 'Гимн школы'},
        ),
        migrations.AlterModelOptions(
            name='maktab_nizomi',
            options={'verbose_name': 'Устав школы', 'verbose_name_plural': 'Устав школы'},
        ),
        migrations.AlterModelOptions(
            name='oquvchilarni_qabul_qilish',
            options={'verbose_name': 'Принятие учеников в школу', 'verbose_name_plural': 'Принятие учеников в школу'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото галерея'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='prezident_qarori',
            options={'verbose_name': 'Указ президента', 'verbose_name_plural': 'Указы президента'},
        ),
        migrations.AlterModelOptions(
            name='principal',
            options={'verbose_name': 'Директор', 'verbose_name_plural': 'Директор'},
        ),
        migrations.AlterModelOptions(
            name='qongiroqlar_jadvali',
            options={'verbose_name': 'Расписание звонков', 'verbose_name_plural': 'Расписание звонков'},
        ),
        migrations.AlterModelOptions(
            name='qubul_kunlari',
            options={'verbose_name': 'Дни приема', 'verbose_name_plural': 'Дни приема'},
        ),
        migrations.AlterModelOptions(
            name='tarkibiy_tuzilma',
            options={'verbose_name': 'Структурная организация', 'verbose_name_plural': 'Структурная организация'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AlterModelOptions(
            name='tugaraklar',
            options={'verbose_name': 'Кружки', 'verbose_name_plural': 'Кружки'},
        ),
        migrations.AlterModelOptions(
            name='xalq_talim',
            options={'verbose_name': 'Министерство образования', 'verbose_name_plural': 'Министерство образования'},
        ),
        migrations.AlterModelOptions(
            name='yil_dasturi',
            options={'verbose_name': 'Программа года', 'verbose_name_plural': 'Программа года'},
        ),
    ]
