# Generated by Django 5.1.5 on 2025-02-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_activist_options_alter_administrators_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activist',
            name='field',
        ),
        migrations.AddField(
            model_name='activist',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activist',
            name='name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
