# Generated by Django 5.1.5 on 2025-02-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_activist_field_activist_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
            ],
            options={
                'verbose_name': 'Главная карусель',
                'verbose_name_plural': 'Главная карусель',
            },
        ),
    ]
