# Generated by Django 5.1.5 on 2025-03-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_sportchi_photo_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportchi',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sportchi',
            name='name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
