# Generated by Django 5.1.5 on 2025-03-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_sportchi_name_ru_sportchi_name_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Galereya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('video', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='video_galereya_images/')),
            ],
            options={
                'verbose_name': 'Видео галерея',
                'verbose_name_plural': 'Видео галерея',
            },
        ),
    ]
