# Generated by Django 5.1.5 on 2025-03-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_popular_alter_tugaraklar_category_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
